# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 434)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 380, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 372, 278))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_X = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout.addWidget(self.label_X)
        self.spinBoxX = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxX.setMinimum(1)
        self.spinBoxX.setMaximum(30)
        self.spinBoxX.setProperty("value", 8)
        self.spinBoxX.setObjectName("spinBoxX")
        self.horizontalLayout.addWidget(self.spinBoxX)
        self.label_Y = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout.addWidget(self.label_Y)
        self.spinBoxY = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxY.setMinimum(1)
        self.spinBoxY.setMaximum(20)
        self.spinBoxY.setProperty("value", 6)
        self.spinBoxY.setObjectName("spinBoxY")
        self.horizontalLayout.addWidget(self.spinBoxY)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_1.setProperty("value", 3)
        self.spinBox_1.setObjectName("spinBox_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_2.setProperty("value", 3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBox_Partition = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_Partition.setMinimum(1)
        self.spinBox_Partition.setMaximum(10)
        self.spinBox_Partition.setProperty("value", 4)
        self.spinBox_Partition.setObjectName("spinBox_Partition")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_Partition)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_Climates = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_Climates.setObjectName("comboBox_Climates")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_Climates)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Укажите размеры поля:"))
        self.label_X.setText(_translate("Dialog", "Ширина:"))
        self.label_Y.setText(_translate("Dialog", "Высота:"))
        self.label_2.setText(_translate("Dialog", "Ёлки"))
        self.label_3.setText(_translate("Dialog", "Клёны"))
        self.label_6.setText(_translate("Dialog", "Точность"))
        self.label_7.setText(_translate("Dialog", "Тип климата:"))

